course = "mooc-programming-25"

[exercises.part04-01_hello_visual_studio_code]
id = 272896
checksum = "53f03b6ad926b8a798faf5acc5c1c1b5"

[exercises.part04-02_line]
id = 272891
checksum = "d74744a81be733c6e8bdfc4d61aedd3d"

[exercises.part04-03_box_of_hashes]
id = 272928
checksum = "2ad5ccea27a7dc0aeb9a160653c6a6e2"

[exercises.part04-04_square_of_hashes]
id = 272922
checksum = "0d8c756c7849f44be46d86255dfc7e20"

[exercises.part04-05_square]
id = 272898
checksum = "656bd123c3abcd5308f32f2facbf10a3"

[exercises.part04-06_triangle]
id = 272907
checksum = "e1cd790d29d224e62f8a9b9fffdf71e2"

[exercises.part04-07_shape]
id = 272921
checksum = "48473fc896ec8a81ebf7d74a61e8caa6"

[exercises.part04-08_spruce]
id = 272903
checksum = "473dea7561a5d99957237a496f1bd001"

[exercises.part04-09_greatest_number]
id = 272918
checksum = "851b802b108fcb725314a6bfc515099a"

[exercises.part04-10_same_characters]
id = 272927
checksum = "22bb796e39ea2b330e13b259bae47ab2"

[exercises.part04-11_first_second_last]
id = 272909
checksum = "2e96877cddd73f1c1c59492d1a0c9b40"

[exercises.part04-12_change_value_of_item]
id = 272919
checksum = "517fdd26d4eca78d44ae452f0371ac61"

[exercises.part04-13_add_items_to_list]
id = 272926
checksum = "d82d708ac36a01721afe2f65cf1a65d7"

[exercises.part04-14_addition_and_removal]
id = 272900
checksum = "0106c35f0f0e7543f3413c4f2189f295"

[exercises.part04-15_same_word_twice]
id = 272908
checksum = "d95508225b8d45f01551f1846e6b0242"

[exercises.part04-16_list_twice]
id = 272897
checksum = "6ccbc749edad6c6d5e7dce779f670604"

[exercises.part04-17_length_of_list]
id = 272893
checksum = "9cf301b09fb83f206150464f85ccd02a"

[exercises.part04-18_mean]
id = 272904
checksum = "01b651dbdb6640536c204869fcd8b00c"

[exercises.part04-19_range_of_list]
id = 272902
checksum = "1e08e6ac5c0c63ebc66d9d69e84476f4"

[exercises.part04-20_star_studded]
id = 272920
checksum = "fbcab2d08087887a4d8b27feb6788e11"

[exercises.part04-21_negative_to_positive]
id = 272925
checksum = "4f046841f26c7e9b7ab128f206d70494"

[exercises.part04-22_list_of_stars]
id = 272901
checksum = "2108df6cb9ee42c1dd995ae0847a3a38"

[exercises.part04-23_anagrams]
id = 272924
checksum = "aff92c0c7f18fbbe382b8484dae4d91a"

[exercises.part04-24_palindromes]
id = 272917
checksum = "5a2724a0a9d96815de6806e333fff4aa"

[exercises.part04-25_sum_of_positives]
id = 272915
checksum = "a0268dc15b691c52f7db957c324f95f8"

[exercises.part04-26_even_numbers]
id = 272913
checksum = "48dee3ef1f8993e6a973a4c9611b3bed"

[exercises.part04-27_sum_of_lists]
id = 272914
checksum = "e48b09162a829eaa015ed6cca8f7fe0a"

[exercises.part04-28_distinct_numbers]
id = 272906
checksum = "d401fdf63f3f3e98fecbe462f9ea94be"

[exercises.part04-29_length_of_longest]
id = 272892
checksum = "b5d8cbdcc4306cea77cf2ab83a79f30b"

[exercises.part04-30_shortest_in_list]
id = 272905
checksum = "150226ddf9bf11b44cdfbfa4701ddaa0"

[exercises.part04-31_all_longest_in_list]
id = 272899
checksum = "baa5ec110068d815440487becc1fef75"

[exercises.part04-32_integers_to_strings]
id = 272894
checksum = "533cd68e600a75c701abb57ff38808f5"

[exercises.part04-33_everything_reversed]
id = 272911
checksum = "e4daefb8fb1ef5d6450da93caab1929e"

[exercises.part04-34_most_common_character]
id = 272923
checksum = "f752acda538ab84b07917ad5fe4272a8"

[exercises.part04-35_no_vowels_allowed]
id = 272910
checksum = "919a73b7eef401b37241fcef8ed32061"

[exercises.part04-36_no_shouting_allowed]
id = 272912
checksum = "35ebe2fbbb19202bcdd85f56d4161397"

[exercises.part04-37_neighbours_in_list]
id = 272916
checksum = "f3d4614493e0c29e7262da19266dd2cb"

[exercises.part04-38_grade_statistics]
id = 272895
checksum = "a0659c42eec2020cabde74b1d1873d08"

[exercises.part05-01_longest_string]
id = 272859
checksum = "27bfd4904f6f7fce0948d3ea35f8a110"

[exercises.part05-02_number_of_elements]
id = 272864
checksum = "daa5bfff71ba9901481f670ee8065e96"

[exercises.part05-03_go]
id = 272877
checksum = "825aa0b64f9de5d9cde4e32f9988a93f"

[exercises.part05-04_sudoku_row]
id = 272860
checksum = "0fdc4c67ccae6e33480418eb380e416d"

[exercises.part05-05_sudoku_column]
id = 272868
checksum = "7ea5c1b5783cbd4b3e8db8d7ad38b53d"

[exercises.part05-06_sudoku_block]
id = 272867
checksum = "f9f7cc09e2657e8f222371f620d9dfbb"

[exercises.part05-07_sudoku_grid]
id = 272865
checksum = "667bfcafa21b221fbc167499fdd02da2"

[exercises.part05-08_items_multiplied_by_two]
id = 272852
checksum = "2d2384800c0d59428ce7d1a25deb7162"

[exercises.part05-09_remove_smallest]
id = 272862
checksum = "5b67e1d4437d5dfe610d3c2eec1a5ed5"

[exercises.part05-10_sudoku_print_and_add]
id = 272878
checksum = "4a5a08b0ff30ae36013361c0a6e7485e"

[exercises.part05-11_sudoku_add_to_copy]
id = 272873
checksum = "09fb363fec1f60a9ccbc0a12f10eca00"

[exercises.part05-12_tic_tac_toe]
id = 272856
checksum = "8f55f10b7d033dd70f6a4f74fefbe9ff"

[exercises.part05-13_transpose_matrix]
id = 272876
checksum = "fd4395482ecf42678ae836be6e85db94"

[exercises.part05-14_times_ten]
id = 272874
checksum = "971fea5d40fea666a02a0308d62387b7"

[exercises.part05-15_factorials]
id = 272861
checksum = "4d9f54a425e3a67e38590b5dbb01f3a9"

[exercises.part05-16_histogram]
id = 272869
checksum = "2481bde05b6d22b5319c8e960e52a440"

[exercises.part05-17_phone_book_v1]
id = 272854
checksum = "0648d4f9b1a7b5e73ef4753ae819b1a6"

[exercises.part05-18_phone_book_v2]
id = 272857
checksum = "8f810c22fdd0548f27303234847c94b4"

[exercises.part05-19_invert_dictionary]
id = 272855
checksum = "9d7be9e7653cc54a47f58b06e9b22baa"

[exercises.part05-20_numbers_spelled_out]
id = 272858
checksum = "e35d8671dbc20736f65063d672f88f85"

[exercises.part05-21_movie_database]
id = 272872
checksum = "9662cac645d8335994fe842be6d101c0"

[exercises.part05-22_find_movies]
id = 272863
checksum = "5f7310035359bed7b9bbfc90c8e19ac6"

[exercises.part05-23_create_tuple]
id = 272871
checksum = "4493c2d1f146469d8ddfa3f48bfa278d"

[exercises.part05-24_oldest_person]
id = 272853
checksum = "34d827930b2ba8e29f5914c24b04a9b7"

[exercises.part05-25_older_people]
id = 272866
checksum = "dd08c2cbd9a60168a0ea077c9f3901d1"

[exercises.part05-26_student_database]
id = 272875
checksum = "2340604c86baff1659158177ee516486"

[exercises.part05-27_letter_square]
id = 272870
checksum = "cb44a7e4ee917326d644868da2fd9668"

[exercises.part06-01_largest_number]
id = 272995
checksum = "128f64f61b34cdeec87708de88a4f9f2"

[exercises.part06-02_fruit_market]
id = 272981
checksum = "dc40a9c36ce4038ee8100bf5498661dd"

[exercises.part06-03_matrix]
id = 272977
checksum = "4ca789bffb78151c36976c7ef8309757"

[exercises.part06-04_course_grading_part_1]
id = 272980
checksum = "f35fad9f23560cad46fa224a80b946bc"

[exercises.part06-05_course_grading_part_2]
id = 272992
checksum = "fef60ecdc1aca0b6e24d7a4befd63664"

[exercises.part06-06_course_grading_part_3]
id = 272986
checksum = "e65f42cdd26f9a438b783c494644d201"

[exercises.part06-07_spellchecker]
id = 272994
checksum = "088b17d99e1c2c5b09593131a9c0d6cd"

[exercises.part06-08_recipe_search]
id = 272987
checksum = "4d9a4ab2e3b1b7fe0ceddac2318e05e2"

[exercises.part06-09_city_bikes]
id = 272990
checksum = "d40a7c30e1a54b037676efbfd086b130"

[exercises.part06-10_inscription]
id = 272985
checksum = "a15aa87ce7179f4985a59b911cc05f1d"

[exercises.part06-11_diary]
id = 272984
checksum = "bd775e74ffbf5f33d346ce56b26c47a2"

[exercises.part06-12_filtering_file_contents]
id = 272993
checksum = "97ac5cf1169e630c0e03b66f78c58534"

[exercises.part06-13_store_personal_data]
id = 272978
checksum = "be9444864d1f253ca7af07eaeca1a204"

[exercises.part06-14_course_grading_part_4]
id = 272979
checksum = "f394a67c340097c6605ec49d86ae6076"

[exercises.part06-15_word_search]
id = 272983
checksum = "d8921112956d26782ac7f20887d9f309"

[exercises.part06-16_dictionary_file]
id = 272989
checksum = "b1440d20b21cfec94412c5eae17671e1"

[exercises.part06-17_read_input]
id = 272982
checksum = "9cfa27b8753fb182c9fb0229b67ffb37"

[exercises.part06-18_parameter_validation]
id = 272991
checksum = "c4e43deda7163ffa06741f00b3e8abdd"

[exercises.part06-19_incorrect_lottery_numbers]
id = 272988
checksum = "7984bd56e31eb50c346535ae400cf098"

[exercises.part07-01_hypotenuse]
id = 273042
checksum = "943685b853591b2b99d26943437ed2e4"

[exercises.part07-02_special_characters]
id = 273032
checksum = "cb13f824fcb36019c2d4d7762f2ad2e6"

[exercises.part07-03_fractions]
id = 273029
checksum = "2663b23a4209e7245dedb484ac8584c1"

[exercises.part07-04_lottery_numbers]
id = 273039
checksum = "53acc1d6ae2300162ad26794a486cf7f"

[exercises.part07-05_password_generator_part_1]
id = 273028
checksum = "d434c3f6db036568d35ed587c0c493cb"

[exercises.part07-06_password_generator_part_2]
id = 273044
checksum = "0f6d0fb3d833a1401eb4fbcbbc4eec23"

[exercises.part07-07_dice_roller]
id = 273035
checksum = "d11e7b7a578c57a7b35d4b47bfa61ded"

[exercises.part07-08_random_words]
id = 273038
checksum = "a0bc802f27442564165e80ad6c79a962"

[exercises.part07-09_how_old]
id = 273040
checksum = "27d20c141654e3115946ec25b5dafffb"

[exercises.part07-10_valid_pic]
id = 273037
checksum = "547883b55edc9aadad1786fc3ac7ee05"

[exercises.part07-11_screen_time]
id = 273027
checksum = "7f8299bea8bf8067e6703e2a82b982c1"

[exercises.part07-12_json_files]
id = 273041
checksum = "cdb9bafdea65e7eca22c15fef926b193"

[exercises.part07-13_course_statistics]
id = 273033
checksum = "df6ec1027c08acfb1ee3ca6ccea36daf"

[exercises.part07-14_who_cheated]
id = 273036
checksum = "5dd42233d4452867df18c4f324ef9647"

[exercises.part07-15_who_cheated_2]
id = 273034
checksum = "872f68aaaf37df4e83532c31d01f9b08"

[exercises.part07-16_spellchecker_2]
id = 273043
checksum = "b50379047603d3c031ae5a7c4a991347"

[exercises.part07-17_string_helper]
id = 273030
checksum = "12b0968c95c2ca1ff2446226bac7361a"

[exercises.part07-18_own_programming_language]
id = 273031
checksum = "85f451181b069b4e31f6c8b45b800cde"

[exercises.part08-01_smallest_average]
id = 272962
checksum = "7b173687bf0adebc4a486a68f6c32031"

[exercises.part08-02_row_sums]
id = 272975
checksum = "d9973e48318dc29c3327e7897d41ec80"

[exercises.part08-03_list_years]
id = 272968
checksum = "34204b1e729dbe3f9e230ece01aff8bb"

[exercises.part08-04_shopping_list]
id = 272976
checksum = "ae99378be7d856870fd842230850b805"

[exercises.part08-05_book]
id = 272963
checksum = "aac905bf98e296530348a26ce1d62953"

[exercises.part08-06_three_classes]
id = 272965
checksum = "db0a8040524583a0b511483cf1ce31a0"

[exercises.part08-07_pet]
id = 272971
checksum = "b7a475be3b4f573b0e662c62d56c53db"

[exercises.part08-08_older_book]
id = 272973
checksum = "ec8edbf83ca00f4ec521f446208bbb97"

[exercises.part08-09_books_of_genre]
id = 272972
checksum = "8a92d4e749d53c617b4e0624f9604e43"

[exercises.part08-10_decreasing_counter]
id = 272974
checksum = "baa34ecdf760cdde32cc3fbdf5536d12"

[exercises.part08-11_first_and_last_name]
id = 272970
checksum = "b106215b92f30bfe45dab2b229bc4fa7"

[exercises.part08-12_number_stats]
id = 272969
checksum = "7b15d1eb9de2227eea1a319ac5a9b71b"

[exercises.part08-13_stopwatch]
id = 272966
checksum = "2d59af6633c662644f62bddb79d2a0ce"

[exercises.part08-14_clock]
id = 272967
checksum = "9326d9c6edfc221351a6d919b01f4b54"

[exercises.part08-15_lunchcard]
id = 272961
checksum = "de1dd39ddb02a80fc5ac43d905a0207f"

[exercises.part08-16_series]
id = 272964
checksum = "cc7e178145f70ef2440ffcf972d5e79e"

[exercises.part09-01_fastest_car]
id = 272782
checksum = "5c92c0748d08f4c30991ab9ce461af58"

[exercises.part09-02_passing_submissions]
id = 272794
checksum = "fd62c8b5668c6554acbea13cc44efc44"

[exercises.part09-03_baby_centre]
id = 272780
checksum = "8a1920343eb9a76b20da5a1108c9e6df"

[exercises.part09-04_lunchcard_and_paymentterminal]
id = 272787
checksum = "cffc0c94e6e88b59f6e9e39b459fa812"

[exercises.part09-05_comparing_properties]
id = 272792
checksum = "f84df8c676e5754e99578443bc6ec385"

[exercises.part09-06_pets]
id = 272789
checksum = "5d59bed6b1812f2810cb8cce176f953f"

[exercises.part09-07_box_of_presents]
id = 272783
checksum = "12134adc29f90795f814b7b6148f84b9"

[exercises.part09-08_shortest_in_room]
id = 272790
checksum = "79b612f68fabb9ce422ad4233f2c3b6a"

[exercises.part09-09_car]
id = 272781
checksum = "2b97108b7802ff72a4ab794926e817ef"

[exercises.part09-10_recording]
id = 272784
checksum = "b0bb4fa38607ad2760e9cfdffed939c7"

[exercises.part09-11_weather_station]
id = 272786
checksum = "4c95dfa9122553c816af249dd6fda33e"

[exercises.part09-12_service_charge]
id = 272785
checksum = "f5f0fb9cdd5ba3769ce46030f7b298b7"

[exercises.part09-13_postcodes]
id = 272793
checksum = "a664fc51b4042799d0a122f494da72d4"

[exercises.part09-14_list_helper]
id = 272791
checksum = "60cae6fb12085068d1effba1b960f411"

[exercises.part09-15_item_suitcase_hold]
id = 272788
checksum = "9887a7260d0779c3546e5a57bb0feebd"

[exercises.part10-01_laptop_computer]
id = 272888
checksum = "d3cc52fa293407a3b9f5c530048c6985"

[exercises.part10-02_game_museum]
id = 272879
checksum = "d6879c3d7ab4bb5ba9f8ef1a71dc764f"

[exercises.part10-03_areas]
id = 272883
checksum = "92a26ec165d30412af3fbe6677403e4d"

[exercises.part10-04_word_game]
id = 272881
checksum = "b7b87f0778c36c81eee64a27c7630687"

[exercises.part10-05_supergroup]
id = 272880
checksum = "ebcf56154970a9cb56641f058c3f17fa"

[exercises.part10-06_secret_magic_potion]
id = 272886
checksum = "046fc36f18233f55c136b4600ec18f63"

[exercises.part10-07_money]
id = 272884
checksum = "212544ea576eee1770f3086785f65777"

[exercises.part10-08_simple_date]
id = 272885
checksum = "a582e1778b169d42b0abe96dfe3cf7a3"

[exercises.part10-09_iterable_shopping_list]
id = 272889
checksum = "c855e3a427bc472ab5a07c066a19b0ea"

[exercises.part10-10_phone_book_v1]
id = 272890
checksum = "dc5a7c94c16f7c320e5bfb8c1bee6c39"

[exercises.part10-11_phone_book_v2]
id = 272887
checksum = "2d92548a10df72760f7c2960b4be8bbb"

[exercises.part10-12_course_records]
id = 272882
checksum = "91b224b1823a1142dc1d57cbde900236"

[exercises.part11-01_square_roots]
id = 272771
checksum = "aa89bedc5e9cc11c587b93e539f8b1c2"

[exercises.part11-02_rows_of_stars]
id = 272774
checksum = "bf4aa1d7a69a143e2f8ddd0b12c1286f"

[exercises.part11-03_best_exam_result]
id = 272769
checksum = "a37ac598e08fbcf8b25be7aa7064a231"

[exercises.part11-04_lengths]
id = 272765
checksum = "5a1263bb32ac4aa0db5801511e0a3973"

[exercises.part11-05_remove_smaller_than]
id = 272770
checksum = "c243265ad147fe0bd92f4ed08ec7ca6f"

[exercises.part11-06_begin_with_vowel]
id = 272776
checksum = "b5f245549c4c4d62a5be4ff919a4bf79"

[exercises.part11-07_lottery_numbers]
id = 272766
checksum = "41b87e13580750598d62029525aa4db6"

[exercises.part11-08_filter_forbidden]
id = 272762
checksum = "6ef0aa880963298a468d92bb1f762693"

[exercises.part11-09_products_in_shopping_list]
id = 272773
checksum = "43a878e513b194b3072f26bda69bd91d"

[exercises.part11-10_cheaper_properties]
id = 272764
checksum = "18a35ddac39ea62be37dea9bd0734312"

[exercises.part11-11_lengths_of_strings]
id = 272772
checksum = "7e3f1f525627981c335ec23aba5734b2"

[exercises.part11-12_most_common_words]
id = 272763
checksum = "4fc32fa9f8bf47c341a55c4d3717a174"

[exercises.part11-13_add_numbers_to_list]
id = 272775
checksum = "e6226316f83a082d991e092284aa720a"

[exercises.part11-14_recursive_sum]
id = 272767
checksum = "2f280dc698875bf799a65abd90f3a63e"

[exercises.part11-15_balanced_brackets]
id = 272778
checksum = "41d56498626fbe6122f101166d772f35"

[exercises.part11-16_greatest_node]
id = 272779
checksum = "5cca20881ca5fa9afd7ef04b63ea9eb0"

[exercises.part11-17_bosses_and_subordinates]
id = 272761
checksum = "419d0b10001105bf92ecdc7bdb6ff862"

[exercises.part11-18_order_book]
id = 272768
checksum = "2cd3d260a4e0da79abde62bb82b8d5c0"

[exercises.part11-19_order_book_application]
id = 272777
checksum = "d45965a0805ce4c77715e8f53925b4ad"

[exercises.part12-01_remaining_stock]
id = 272950
checksum = "9af0113977aed944987d99f53f5ce7e7"

[exercises.part12-02_seasons]
id = 272953
checksum = "7930c36198382db36cfdcb631bae4772"

[exercises.part12-03_ratings]
id = 272957
checksum = "822e1952edb4c40ced4ca77d9f47942f"

[exercises.part12-04_climbing_route]
id = 272948
checksum = "f21c3b63d5a7715c4e9d9d5ad8f24c28"

[exercises.part12-05_climbing_areas]
id = 272949
checksum = "44b2d24ab6b7543f226b0370f7bb8ab8"

[exercises.part12-06_ballplayers]
id = 272960
checksum = "66751d7b1f1206f49e0f8cf920dda0f3"

[exercises.part12-07_product_search]
id = 272954
checksum = "1d6d4b762f4b8ac0bd1f3ace1c3d14e5"

[exercises.part12-08_even_numbers]
id = 272946
checksum = "ae5f6362b96ba0f63084e1a62b34f8a5"

[exercises.part12-09_prime_numbers]
id = 272951
checksum = "769469c5b63d1deaaa91bee40d93f124"

[exercises.part12-10_random_words]
id = 272959
checksum = "cff793b5259980ee2f7336ec2c665e4c"

[exercises.part12-11_attempted_courses]
id = 272955
checksum = "3c58aedfa6d8d5b34df86c2f300f5404"

[exercises.part12-12_filtering_attempts]
id = 272956
checksum = "fa9ce4d1d7e3ca511eb489beb850209b"

[exercises.part12-13_credits]
id = 272958
checksum = "c5941f3002cea8f360c210ebecfb2011"

[exercises.part12-14_regular_expressions]
id = 272947
checksum = "45f5764fda4e31c2570e0d8295e26434"

[exercises.part12-15_hockey_statistics]
id = 272952
checksum = "3e680f7db93b93194fded3654947f8b2"
